# Drivers
CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_SENSOR=y
CONFIG_ADC=y
CONFIG_PRINTK=y

CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# Serial console commands: thr, open, gains, status
CONFIG_SHELL=y